module QmkNix.Render.Common
  ( padR
  , indent
  , generated
  , int
  ) where

import Data.Text (Text)
import Data.Text qualified as T

padR :: Int -> Text -> Text
padR n t = t <> T.replicate (max 0 (n - T.length t)) " "

indent :: Int -> Text -> Text
indent n t = T.replicate n " " <> t

generated :: Text -> Text
generated prefix = prefix <> " Generated by qmk-nix. Do not edit."

int :: Int -> Text
int = T.pack . show
