// Generated by qmk-nix. Do not edit.
#include QMK_KEYBOARD_H
#include "keychron_common.h"
#include "qmk_nix_layers.h"

// clang-format off
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [LAYER_BASE] = LAYOUT_tenkey_27(
        KC_MUTE, KC_ESC, KC_DEL, KC_TAB, KC_BSPC,
        MC_1, KC_NUM, KC_PSLS, KC_PAST, KC_PMNS,
        MC_2, KC_P7, KC_P8, KC_P9, KC_PPLS,
        MC_3, KC_P4, KC_P5, KC_P6,
        MC_4, KC_P1, KC_P2, KC_P3, KC_PENT,
        MO(31), KC_P0, KC_PDOT
    ),
    [LAYER_DESIGN_TOOLS] = LAYOUT_tenkey_27(
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS
    ),
    [LAYER_ILLUSTRATOR] = LAYOUT_tenkey_27(
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_PGUP, KC_TRNS, KC_TRNS,
        KC_TRNS, LGUI(KC_PGUP), KC_TRNS, LGUI(KC_PGDN),
        KC_TRNS, KC_TRNS, KC_PGDN, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS
    ),
    [LAYER_FN] = LAYOUT_tenkey_27(
        UG_TOGG, BT_HST1, BT_HST2, BT_HST3, P2P4G,
        QMK_NIX_CYCLE_APP, UG_NEXT, UG_VALU, UG_HUEU, KC_TRNS,
        KC_TRNS, UG_PREV, UG_VALD, UG_HUED, KC_TRNS,
        KC_TRNS, UG_SATU, UG_SPDU, KC_MPRV,
        KC_TRNS, UG_SATD, UG_SPDD, KC_MPLY, QK_BOOT,
        KC_TRNS, UG_TOGG, KC_MNXT
    ),
};
// clang-format on

#if defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
    [LAYER_BASE] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) },
    [LAYER_DESIGN_TOOLS] = { ENCODER_CCW_CW(LGUI(KC_MINS), LGUI(KC_EQL)) },
    [LAYER_ILLUSTRATOR] = { ENCODER_CCW_CW(KC_TRNS, KC_TRNS) },
    [LAYER_FN] = { ENCODER_CCW_CW(UG_VALD, UG_VALU) },
};
#endif

// LED indicator data — only app layers contribute.
typedef struct { uint8_t led; uint8_t r; uint8_t g; uint8_t b; } qmk_nix_led_t;
typedef struct { const qmk_nix_led_t *leds; uint8_t count; } qmk_nix_led_set_t;

static const qmk_nix_led_t qmk_nix_leds_illustrator[] = {
    { 20, 165, 42, 0 },
    { 15, 165, 42, 0 },
    { 17, 165, 42, 0 },
    { 11, 165, 42, 0 },
};

const qmk_nix_led_set_t qmk_nix_indicators_per_layer[QMK_NIX_LAYER_COUNT] = {
    [LAYER_ILLUSTRATOR] = { qmk_nix_leds_illustrator, 4 },
};

// Layer-state masks per app, indexed 0..QMK_NIX_APP_COUNT-1.
const layer_state_t qmk_nix_app_masks[] = {
    (layer_state_t)258u, // illustrator
};
