// Generated by qmk-nix. Do not edit.
#pragma once
#include "quantum.h"

#define LAYER_BASE                    0
#define LAYER_DESIGN_TOOLS            1
#define LAYER_ILLUSTRATOR             8
#define LAYER_FN                      31

#define QMK_NIX_LAYER_COUNT           32
#define QMK_NIX_CAT_FIRST             1
#define QMK_NIX_CAT_LAST              7
#define QMK_NIX_APP_FIRST             8
#define QMK_NIX_APP_LAST              30
#define QMK_NIX_APP_COUNT             1

// Custom keycodes used by firmware-stub/qmk_nix_wireless_fallback.c.
enum qmk_nix_custom_keycodes {
    QMK_NIX_CYCLE_APP = SAFE_RANGE,
};
