// Generated by qmk-nix. Do not edit.
#pragma once
#include "quantum.h"

#define LAYER_BASE                    0
#define LAYER_DESIGN_TOOLS            1
#define LAYER_ILLUSTRATOR             8
#define LAYER_FN                      31

#define QMK_NIX_LAYER_COUNT           32
#define QMK_NIX_CAT_FIRST             1
#define QMK_NIX_CAT_LAST              7
#define QMK_NIX_APP_FIRST             8
#define QMK_NIX_APP_LAST              30
#define QMK_NIX_APP_COUNT             1

// Custom keycodes used by firmware-stub/qmk_nix_wireless_fallback.c.
enum qmk_nix_custom_keycodes {
    QMK_NIX_CYCLE_APP = SAFE_RANGE,
    QMK_NIX_SLOT_KEY_0,
    QMK_NIX_SLOT_KEY_1,
    QMK_NIX_SLOT_KEY_2,
    QMK_NIX_SLOT_KEY_3,
    QMK_NIX_SLOT_KEY_4,
    QMK_NIX_SLOT_KEY_5,
    QMK_NIX_SLOT_KEY_6,
    QMK_NIX_SLOT_KEY_7,
    QMK_NIX_SLOT_KEY_8,
    QMK_NIX_SLOT_KEY_9,
    QMK_NIX_SLOT_KEY_10,
    QMK_NIX_SLOT_KEY_11,
    QMK_NIX_SLOT_KEY_12,
    QMK_NIX_SLOT_KEY_13,
    QMK_NIX_SLOT_KEY_14,
    QMK_NIX_SLOT_KEY_15,
    QMK_NIX_SLOT_KEY_16,
    QMK_NIX_SLOT_KEY_17,
    QMK_NIX_SLOT_KEY_18,
    QMK_NIX_SLOT_KEY_19,
    QMK_NIX_SLOT_KEY_20,
    QMK_NIX_SLOT_KEY_21,
    QMK_NIX_SLOT_KEY_22,
    QMK_NIX_SLOT_KEY_23,
    QMK_NIX_SLOT_KEY_24,
    QMK_NIX_SLOT_KEY_25,
};

#define QMK_NIX_SLOT_KEY_FIRST QMK_NIX_SLOT_KEY_0
#define QMK_NIX_SLOT_KEY_LAST  QMK_NIX_SLOT_KEY_25
#define QMK_NIX_COGCAST_ENABLED 1
